### ISSUE TITLE
How to build project?

### ISSUE THREAD

**Issue by tuturox91** [PureDark/Skyrim-Upscaler#10]
Im donwloaded cmake and downloaded vcpkg. Im have visual studio 2019, and im change in Build Release.bat. path to vcpkg. But I still haven't figured out how to put it all together. I very, very wanna use this mod in Skyrim mod pack.

**Comment by ScrPotato** [comment]
just run the bat it should to the work

**Comment by KhazP** [comment]
> just run the bat it should do the work

Weird, after pressing the bat file it says

The system cannot find the file specified.
'cmake' is not recognized as an internal or external command,
operable program or batch file.
'#if' is not recognized as an internal or external command,
operable program or batch file.
'cmake' is not recognized as an internal or external command,
operable program or batch file.
'#if' is not recognized as an internal or external command,
operable program or batch file.
File not found - *.dll
0 File(s) copied
File not found - *.pdb
0 File(s) copied
File not found - package
0 File(s) copied
Press any key to continue . . .

**Comment by reanorius** [comment]
+1

**Comment by ScrPotato** [comment]
you didn't set your cmake path. look up setting env variables on google 
EDIT: or you didn't install cmake

**Comment by tuturox91** [comment]
![image](https://user-images.githubusercontent.com/51265345/205465578-892afb9c-8870-46b4-a368-6e3589bfbc5a.png)

And im change in Build Release.bat path to vcpkg.cmake (maybe im not write install vcpkg? 

![image](https://user-images.githubusercontent.com/51265345/205465633-a9845b35-07fa-46a0-9adb-deb072f9c9c4.png)

**Comment by ScrPotato** [comment]
yeah i think its related to vr support which is being worked on

**Comment by PureDark** [comment]
> 

You got the wrong ImGui version maybe, ImGuiKey is just type def int, there shouldn't be issue converting int to ImGuiKey.
 
If you guys haven't got experience with cmake, vcpkg, it's no point trying to compile it, cuz this project will not just work if you compile it, it needs my other plugin for bridging DLSS/FSR2/XeSS which I haven't released publicly.

**Comment by rezatitan7** [comment]
Hi dear @PureDark, when can we expect the first beta\pre-release version of DLSS/FSR2/XeSS for Skyrim SE/AE/VR? Thank you for your hard work ❤.

**Comment by tuturox91** [comment]
> > EDIT: I tried to compile myself and there are some errors which make it uncompileable. the error currently is: on the file SettingGUI.cpp "void ProcessEvent(ImGuiKey)': cannot convert argument 1 from 'int' to 'ImGuiKey'" line (76,13)
> 
> You got the wrong ImGui version maybe, ImGuiKey is just type def int, there shouldn't be issue converting int to ImGuiKey.
> 
> If you guys haven't got experience with cmake, vcpkg, it's no point trying to compile it, cuz this project will not just work if you compile it, it needs my other plugin for bridging DLSS/FSR2/XeSS which I haven't released publicly.

Anyway, thanks for what you do!

**Comment by davidm71** [comment]
I myself am playing with VS Code 2022 and trying to figure out vcpkg and almost have it figured out but without the dlaa plugin its not going to compile? So whats point in trying to compile it. Was at least a good learning experience.

**Comment by PureDark** [comment]
> I myself am playing with VS Code 2022 and trying to figure out vcpkg and almost have it figured out but without the dlaa plugin its not going to compile? So whats point in trying to compile it. Was at least a good learning experience.

What? This project compiles on its own. 
What I said was SkyrimUpscaler.dll won't work without the dependencies.
