### ISSUE TITLE
Skyrim VR: getting error after installing Address Library for SKSE Plugins

### ISSUE THREAD

**Issue by hkirsman** [PureDark/Skyrim-Upscaler#11]
I got this error after adding "Address Library for SKSE Plugins"
![SkyrimUpscalerDll error](https://user-images.githubusercontent.com/492375/209647972-fc25c476-4f6d-42e9-9c3a-dc5a56c8d5c6.PNG)

So I downloaded also this plugin which actually contains only the CSV it's complaining about: https://www.nexusmods.com/skyrimspecialedition/mods/58101

So this is my current setup and got rid of the error:
![solution](https://user-images.githubusercontent.com/492375/209647990-bfe810b2-c07b-429f-8563-7dd42527eae6.PNG)

For some reason, the game still does not start. I see Skyrim window being created, the resolution looks different (and scretched out) than normal and then it closes and that's it:
![Capture2](https://user-images.githubusercontent.com/492375/209648677-9f5c509b-aeee-4d80-825f-6b12fc5bd7c3.PNG)

**Comment by BeigeAnimal** [comment]
It's been a week so I don't know if you're still having this issue but remove the Non-VR Address library, that's probably what's causing issues.

**Comment by hkirsman** [comment]
I had to use the VR version of upscaler - didn't know it existed https://www.nexusmods.com/skyrimspecialedition/mods/82179
