### ISSUE TITLE
If any VR testing is needed maybe I could help

### ISSUE THREAD

**Issue by hkirsman** [PureDark/Skyrim-Upscaler#9]
I have this 300 modlist installed ( https://www.nexusmods.com/skyrimspecialedition/mods/69646/ ), 3090 as GPU, VR headset is Quest 2. FPS is about 40-50 outside so would be interesting to see how this affects it. I've been playing for few months with this setup, some crashes here and there but still quite stable I'd say. I would probably not want to adjust any mods as I'm still playing the game through but if it's about replacing some DLL's and putting it back later, then I'd be happy to give feedback.

**Comment by reanorius** [comment]
I just want to get this mod already... It's been a while.

**Comment by hkirsman** [comment]
I'd say it will take as long as it takes. Let's be happy to have it when we do. But I don't want to start a thread here on another topic. I just wanted to help out with testing if possible.

**Comment by reanorius** [comment]
Yeah, same here. As much as I want this to be finished, I'd love to help testing it first. I run a very heavy modlist (2500+ mods) and most of them are graphics improvements, so should be able to provide some good metrics.

**Comment by PureDark** [comment]
There's a test build on my [patreon](https://www.patreon.com/PureDark), if you really want to test, but I'd say it will be probably out in a few days. 
Also that version is for flat Skyrim with ENB. VR version is on discord for testing, and I don't currently need more testers.

**Comment by reanorius** [comment]
Probably not more testers, but definitely need more Patreon supporters, right? Wish you posted this sooner, I'd Patreon you from here all the way to the moon. Flat Skyrim with ENB is what I play most of the time. Thanks again.

**Comment by PureDark** [comment]
> Probably not more testers, but definitely need more Patreon supporters, right? Wish you posted this sooner, I'd Patreon you from here all the way to the moon. Flat Skyrim with ENB is what I play most of the time. Thanks again.

Yeah the build on patreon isn't really for testers cuz most people just want to use it earlier, and testers need to provide assistants and do many troublesome testing and provide me infos.

**Comment by hkirsman** [comment]
@reanorius oh wow, that is heavy modlist!

I'll close this now. I'll report after this comes out and incase I notice something.
